export default ["novak","novakova","svoboda","svobodova","novotny","novotna","dvorak","dvorakova",
    "cerny","cerna","prochazka","prochazkova","kucera","kucerova","vesely","vesela",
    "horak","horakova","nemec","nemcova","marek","markova","pospisil","pospisilova",
    "hajek","hajkova","jelinek","jelinkova","kral","kralova","ruzicka","ruzickova",
    "beneš","benešova","fiala","fialova","sedlacek","sedlackova","dolezal","dolezalova",
    "zeman","zemanova","kral","kralova","kolar","kolarova","benes","benesova",
    "urban","urbanova","vanek","vankova","blaha","blahova","vlcek","vlckova",
    "kraus","krausova","simek","simkova","holub","holubova","cech","cechova",
    "moravec","moravcova","kopecky","kopecka","bartos","bartosova","havel","havlova",
    "fiedler","fiedlerova","vokoun","vokounova","stastny","stastna","valenta","valentova",
    "sykora","sykorova","polak","polakova","mach","machova","zajic","zajicova",
    "kubik","kubikova","krejci","krejcova","malek","malkova","brabec","brabcova",
    "havlicek","havlickova","toman","tomanova","strnad","strnadova","matejka","matejkova",
    "svec","svecova","muzik","muzikova","liska","liskova","kudela","kudelova",
    "sladek","sladkova","dostal","dostalova","balcar","balcarova","cerveny","cervena",
    "capek","capkova","cizek","cizkova","bily","bila","spacek","spackova",
    "burianek","burianekova","zahradnik","zahradnikova","kadlec","kadlecova","stepanek","stepankova"]
